### PR TITLE
CTD materials

### PR DESCRIPTION
**Pull request by HanbaiWang**

### CODE REVIEW

**Review by ShutingQing — APPROVED** [review]
LGTM, after we have the spec, docs, user stories, we can add it on.

**Comment by DanXu-ChinaTelecom** [comment]
LGTM，maybe we need to decide on priorities for the checklist work

**Review by DanXu-ChinaTelecom — APPROVED** [review]

**Review by HanbaiWang — COMMENTED** [review]
LGTM

**Comment by hdamker** [comment]
@ShutingQing @ShutingQing This PR seems to be stalled and overlapping with more recent PRs? Do you want to close it?

**Comment by ShutingQing** [comment]
@HanbaiWang Hanbai, would you please take a look of this?

**Pull request closed without merging**
