### PR TITLE
CTD support material

### PR DESCRIPTION
**Pull request by HanbaiWang**
support material

### CODE REVIEW

**Review by ShutingQing — APPROVED** [review]
LGTM

**Comment by DanXu-ChinaTelecom** [comment]
Good material, help to understand this API

**Comment by hdamker** [comment]
This PR can't be merged by the sub project itself, as @HanbaiWang is the only codeowner (and can't approve his won PRs).
@HanbaiWang to you want my help to get it merged. There are two approvals, so it should be fine.

**Comment by HanbaiWang** [comment]
> This PR can't be merged by the sub project itself, as @HanbaiWang is the only codeowner (and can't approve his won PRs). @HanbaiWang to you want my help to get it merged. There are two approvals, so it should be fine.

Yes, could you please help me to merge this? Btw could you please add @@ShutingQing as another codeowner of this sub project?(as there should be at least 2 code owner of this project?) Thanks a lot.

**Comment by hdamker** [comment]
> Yes, could you please help me to merge this? Btw could you please add @@ShutingQing as another codeowner of this sub project?(as there should be at least 2 code owner of this project?) Thanks a lot.

@HanbaiWang I've created #14 ... as soon you have approved and merged it, @ShutingQing is also codeowner. With her approval you can then merge this PR here.

**Review by ShutingQing — APPROVED** [review]
Thanks Herbert, and thanks Hanbai for the material. The slide looks good to me, detailed in API functions, API definitions, refering related standards elaboration. Approve.

**Pull request merged**
